### ISSUE TITLE
Get serializer from model decorator

### ISSUE THREAD

**Issue by breslavsky** [AndreyZelenskiy/serialize#18]
Thanks for the great job!

Please check the code:

```
@Model(new MyModelSerializer())
export class MyModel {
  @Field() name: string = 'bob';
}

export class MyModelSerializer implements Serializer<MyModel> {
  serialize(source: MyModel): Object {
    return {test: 1};
  }

  deserialize(source: Object): MyModel {
    throw new Error('Not necessary for implementing');
  }
}

console.log(serialize(new MyModel()));
```

Output: `{name: 'bob'}`, but we expected `{test: 1}` because we defined own serializer for `MyModel`

**Comment by AndreyZelenskiy** [comment]
Yes, I checked it and I had the same behavior. When I designed it I thought that it will be used only for a nested model. But now I think I should handle this serializer as a serializer for a type. 
Thank you for the feedback!
I will start implementing it tomorrow and release new patch after it.

Do you have some more improvements for this library? Maybe some features are not very convenient for you

**Comment by breslavsky** [comment]
Andrey, your library is great! We plan to use it in one open source project based on Angular 7. Soon I can send a link. Then I can send you some real cases and suggestions for improvements.

**Comment by breslavsky** [comment]
Andrey, let show you my real case what I am finally want:

```
@Model(new MyModelSerializer())
export class MyModel {
  @Field() name: string[] = 'Bob';
}

export class MyModelSerializer extends ModelSerializer<MyModel> {
  serialize(source: MyModel): Object {
    const obj = super.serialize(source);
    obj['name'].push('Marley');
    return obj;
  }
  constructor() {
    super(MyModel);
  }
}

console.log(serialize(new MyModel()));
```
Expected: `{ name: ['Bob', 'Marley']}`

I am not sure what it is the right way for this. What do you think? Actually, it is some kind of post-processing. I want change structure of object before sending to the server. And want to have one central place for this job based on decorators.

Sure, as the solution I can create special decorators on my side like `@Convert`

```
@Model()
@Convert(new MyModelConverter())
export class MyModel {
  @Field() name: string[] = 'Bob';
}
```

And then `convert(serialize(new MyModel()));`

Thanks for the discussion!

**Comment by AndreyZelenskiy** [comment]
Give me few minutes for check it and write a code demo. I think you are able to solve this problem with a custom serializer for this field only and `@Type` decorator.

**Comment by breslavsky** [comment]
The problem is that some fields can be transformed into new one. E.g.
 
```
@Model(new MyModelSerializer())
export class MyModel {
  @Field() firstName: string[] = 'Bob';
  @Field() lastName: string[] = 'Marley';
}

export class MyModelSerializer extends ModelSerializer<MyModel> {
  serialize(source: MyModel): Object {
    const obj = super.serialize(source);
    return {name: obj.firstName + ' ' + obj.lastName};
  }
  constructor() {
    super(MyModel);
  }
}

console.log(serialize(new MyModel()));
```
Expected: `{name: 'Bob Marley'}`

**Comment by AndreyZelenskiy** [comment]
Yes, I see now. I should take a serializer from a `@Model` decorator, but I think it's not very clean for users and should be named in a different way. I think I am able to create one decorator for both fields and classes, but I don't know how to name it. Do you have any ideas? Maybe `@Converter` or something like that.

**Comment by breslavsky** [comment]
Let's to view http://docs.automapper.org/en/stable/Before-and-after-map-actions.html

I had some experience with `AutoMapper` in `C#`

Probably,

```
@Converter((obj: {[key: string]: any}) => {name: obj.firstName + ' ' + obj.lastName})
export class MyModel {
  @Field() firstName: string = 'Bob';
  @Field() lastName: string = 'Marley';
}
```

**Comment by breslavsky** [comment]
Or `@Mapper((obj: {[key: string]: any}) => {name: obj.firstName + ' ' + obj.lastName}))`

**Comment by AndreyZelenskiy** [comment]
@breslavsky I like a variant with a `@Converter`, but we have to think about deserialization of those models. That's why I want to add a decorator `@Converter` for both fields and classes and put a `Serializer<T>` as a parameter for this decorator. What do you think about it?

**Comment by breslavsky** [comment]
@AndreyZelenskiy will be better to have a code example. 

Did you suggest like this?

```
@Converter(new MyModelSerializer())
export class MyModel {
  @Field() firstName: string = 'Bob';
  @Field() lastName: string = 'Marley';
}

export class MyModelSerializer extends ModelSerializer<MyModel> {
  serialize(source: MyModel): Object {
    const obj = super.serialize(source);
    return {name: obj.firstName + ' ' + obj.lastName};
  }
  constructor() {
    super(MyModel);
  }
}
```

**Comment by AndreyZelenskiy** [comment]
@breslavsky Yes, exactly

**Comment by breslavsky** [comment]
M...in this case I think is more logical use for classes you current decorator `@Model` and for properties `@Type`

```
@Converter(new MyModelSerializer())
export class MyModel {
  @Field() firstName: string = 'Bob';
  @Field() lastName: string = 'Marley';
  @Type(new DateSerializer()) birthday: Date;
}

export class MyModelSerializer extends ModelSerializer<MyModel> {
  serialize(source: MyModel): Object {
    const obj = super.serialize(source);
    return {name: obj.firstName + ' ' + obj.lastName};
  }
  constructor() {
    super(MyModel);
  }
}
```

**Comment by breslavsky** [comment]
And also probably merge some decorators into one

```
@Model({serializer: new MyModelSerializer()})
export class MyModel {
  @Field() firstName: string = 'Bob';
  @Field() lastName: string = 'Marley';
  @Field({name: 'birth_day', serializer: DateSerializer()}) birthDay: Date;
}

```

**Comment by AndreyZelenskiy** [comment]
Yes, but I don't want to get a huge configuration for a decorator. I think it will be better if I provide a possibility to merge decorators by a function call.
Right now, you are able to use `@Field` decorator with this approach.
But I think it isn't very readable.
```typescript
const CustomModel = mergeDecorators(Model(new MyModelSerializer()), After(obj => console.log(obj)));

@CustomModel
export class MyModel {
    @Field() firstName = 'Bob';
    @Field() secondName = 'Marley';
}
```

**Comment by breslavsky** [comment]
I think `huge` configuration is a good solution because in big systems we can have some conflicts or intersections. Let's get as example angular decorators.

```
@NgModule({
  declarations: [],
  imports: [],
  providers: []
})
```

E.g. in my project I created decorators for mock up generation:

```
@Model()
@MockClass()
export class IssueCard {

  @Field()
  @MockField('{{id}}'})
  id: number;

  @Field()
  @MockField('{{issue}}')
  title: string;
```

Having one decorator with flex customization can save place in code.

**Comment by AndreyZelenskiy** [comment]
Maybe I was wrong about this "improvement". Let's have one configuration for each decorator. I think I will leave current decorators in this state, but I should improve a `@Model` decorator. Do you want this `before` and `after` fields only for a debug, or for a changing of a model after or before serialization?

**Comment by breslavsky** [comment]
@AndreyZelenskiy Thanks for the great discussion and best decisions for everybody. I think `after` will be enough and we can only pass the link to the callback without waiting result. I think if `after` will return the fully new value it can break logic.

What do you think?
```
@Model({serializer: new MyModelSerializer(), after: (obj: {[key: string]: any})=> {
    obj['name'] = obj.firstName + ' ' + obj.lastName;
    delete obj['firstName'];
    delete obj['lastName'];
}})
export class MyModel {
  @Field() firstName: string = 'Bob';
  @Field() lastName: string = 'Marley';
  @Field({name: 'birth_day', serializer: new DateSerializer('YYYY-MM-DD')}) birthDay: Date;
}

console.log(serialize(new MyModel()));
```
Expected: `{name: 'Bob Marley', birth_day: '1945-02-06'}`

**Comment by AndreyZelenskiy** [comment]
@breslavsky I think that this `after` method will have the same functionality as a serializer. If you don't mark fields with `@Field` decorator they will be ignored, but it's work only with a default serializer. If you define your own serializer you don't have to use those decorators because of only a default serializer used them. For example, if you define your custom serializer you will have a full model as a parameter in your `serialize` method. So, you are able to choose what fields you will ignore or serialize

**Comment by AndreyZelenskiy** [comment]
@breslavsky You are able to check my PR if you want. I will double check it tomorrow with a fresh eye.

**Comment by breslavsky** [comment]
Sorry, I don't fully understand your position about `after` from my side I think workflow must be:
`Source Typed Object` &rarr; `Serializer` &rarr; `{[key: string]: any}` &rarr; `after` 

Am I right?

**Comment by AndreyZelenskiy** [comment]
Yes, but I spoke about your example.
```typescript
@Model({serializer: new MyModelSerializer(), after: (obj: {[key: string]: any})=> {
    obj['name'] = obj.firstName + ' ' + obj.lastName;
    delete obj['firstName'];
    delete obj['lastName'];
}})
export class MyModel {
  @Field() firstName: string = 'Bob';
  @Field() lastName: string = 'Marley';
  @Field({name: 'birth_day', serializer: new DateSerializer('YYYY-MM-DD')}) birthDay: Date;
}

console.log(serialize(new MyModel()));
```
In this case, we are able to return a new object from the ` MyModelSerializer.serialize()` with the same logic and get expected result from it. I don't want to provide any reference variables. Is it will be something like post-processing we have to get a result from this `after` method as for a post-processing method

**Comment by breslavsky** [comment]
No problem ;-) It means it will be:

```
@Model({serializer: new MyModelSerializer(), after: (obj: {[key: string]: any}) => {
    return {name: obj.firstName + ' ' + obj.lastName, birth_day: obj.birth_day}
}})
export class MyModel {
  @Field() firstName: string = 'Bob';
  @Field() lastName: string = 'Marley';
  @Field({name: 'birth_day', serializer: new DateSerializer('YYYY-MM-DD')}) birthDay: Date;
}
```

Right?

**Comment by AndreyZelenskiy** [comment]
Yes


ср, 30 янв. 2019 г., 17:38 breslavsky notifications@github.com:

**Comment by AndreyZelenskiy** [comment]
@breslavsky I will close this issue after this PR. I think we have to create another ticket with an improvement about `after` and `before` hooks. I think it will be useful, but I have to refactor a little bit for implementing this feature. What do you think about it?

**Comment by breslavsky** [comment]
@AndreyZelenskiy yes, do I need to create a ticket or you will create by your self?

**Comment by AndreyZelenskiy** [comment]
@breslavsky Released patch
