### ISSUE TITLE
Wrong signature for serialize converter

### ISSUE THREAD

**Issue by breslavsky** [AndreyZelenskiy/serialize#22]
Please check error in WebStorm
<img width="812" alt="screenshot 2019-02-04 at 23 56 58" src="https://user-images.githubusercontent.com/8783224/52236739-b36fb400-28d8-11e9-8238-8f504d5e6244.png">

Your current signature is
```
export declare function serialize(model: {
    [key: string]: any;
}): Object;
```
Probably must be
`export declare function serialize(model: Object): {[key: string]: any};`

Because we are waiting for real object and must serialize it into key/value?

**Comment by AndreyZelenskiy** [comment]
Yes, I think you are right. I have to make it generic. Thank you a lot)

**Comment by AndreyZelenskiy** [comment]
@breslavsky What do you think about making all default serializers as singletons instead of creation with a new keyword?

**Comment by AndreyZelenskiy** [comment]
@breslavsky And maybe will be better to create an alternative version of `deserialize` method something like `deserialize(modelConstructor)(json)`?

**Comment by breslavsky** [comment]
@AndreyZelenskiy 

> What do you think about making all default serializers as singletons instead of creation with a new keyword?

I think it is good idea to have constructor, because you can pass additional params. E.g. format for date serialization/deserialization.

> And maybe will be better to create an alternative version of `deserialize` method something like `deserialize(modelConstructor)(json)`?

I think the function `deserialize` must be universal and read serializator from decorator or by default use `ModelSerializer`.

**Comment by AndreyZelenskiy** [comment]
@breslavsky About the first question. I was talking about serializers that already implemented in the library. They don't have a state, that's why I think I am able to create a singleton for them instead of creating every time with a `new`. 

The second one was about your call of `map` function. I think it's not very convenient to create something like this `map(obj => deserialize(obj, Model))` every time. It will be better if you just call map with `map(deserialize(Model))`.

**Comment by breslavsky** [comment]
@AndreyZelenskiy 

> About the first question. I was talking about serializers that already implemented in the library. They don't have a state, that's why I think I am able to create a singleton for them instead of creating every time with a `new`.

> already implemented in the library
It is not fully clear to me...sorry.

> The second one was about your call of `map` function. I think it's not very convenient to create something like this `map(obj => deserialize(obj, Model))` every time. It will be better if you just call map with `map(deserialize(Model))`

Great idea!

**Comment by AndreyZelenskiy** [comment]
Already released)

**Comment by AndreyZelenskiy** [comment]
@breslavsky Could you check it and if it is ok for you I will close an issue?

**Comment by breslavsky** [comment]
Everything is fine! Thanks.
