### ISSUE TITLE
Serialization profiles

### ISSUE THREAD

**Issue by breslavsky** [AndreyZelenskiy/serialize#27]
@AndreyZelenskiy hello again! And thanks a lot for the great library.

We have a special case. Please check the code for the idea.

```typescript
enum SerializeProfiles {
  reference
}

class User {
  @Field() id: number;
  @Field() name: string;
}

class Reference {
  @Field() id: number;
}

@Model()
class Issue {
  @Field({
    serializer: new ModelSerializer(User),
    profiles: {
      [SerializeProfiles.reference]: new ModelSerializer(Reference)
    }
  })
  user: User;
}
const anton = new User();
anton.id = 1;
anton.name = 'Anton';

const issue = new Issue();
issue.user = anton;

// will be used default serializer
console.log(serialize(issue));
{user: {id: 1, name: 'Anton'}}

// will be used serializer from profile
console.log(serialize(issue, SerializeProfiles.reference));
{user: {id: 1}}
```

What do you think? Is it possible?

**Comment by AndreyZelenskiy** [comment]
Hello, Anton! Your idea sounds very interesting to me. 
Do you insist on this API? Maybe, better to provide these profiles to the model. What do you think about it?
 If you provide me more cases I will understand your goals better

**Comment by breslavsky** [comment]
Hello @AndreyZelenskiy! Sorry for the delay, was on vacation ;-)

We are writing a library which can store data into **PouchDB** and we need **different serializers** for serialization and deserialization.

We have one object in memory which must be split into small sub-objects which will be stored into the object database PouchDB separately. 

Check my example:

```typescript
enum SerializeProfiles {
  reference
}

class User {
  @Field() id: number;
  @Field() name: string;
}

class Reference {
  @Field() id: number;
}

@Model()
class Issue {
  @Field() id: number;
  @Field() title: string;
  @Field({
    serializer: new ModelSerializer(User),
    profiles: {
      [SerializeProfiles.reference]: new ModelSerializer(Reference)
    }
  })
  user: User;
}

const anton = new User();
anton.id = 1;
anton.name = 'Anton';

let issue = new Issue();
anton.id = 2;
issue.title = 'Task A';
issue.user = anton;

const doc1 = serialize(anton, SerializeProfiles.reference);
console.log(doc1);
// {id: 1, name: 'Anton'}
db.save(doc1);

const doc2 = serialize(issue, SerializeProfiles.reference);
console.log(doc2);
// {id: 2, title: 'Task A', user: {id: 1}}
// here is magic, I want serialize only 1 level structure of object
db.save(obj2);

// then I wrote special deep loader object from PouchDB
const doc4 = db.get(2);
console.log(doc4);
// {id: 2, title: 'Task A', user: {id: 1}}
issue = deserialize(doc4, Issue);
console.log(issue);
// {id: 2, title: 'Task A', user: {id: 1, name: null}}
issue.deepLoad(db);
console.log(issue);
// {id: 2, title: 'Task A', user: {id: 1, name: 'Anton'}}

// but I can create full export of object, e.g. for save into one json file
const doc3 = serialize(issue));
console.log(doc3);
// {title: 'Task A', user: {id: 1, name: 'Anton'}}
```

**Comment by AndreyZelenskiy** [comment]
Hello, @breslavsky! Sorry for such a long time to answer. I was too busy during the last week. 😢
I think it will be a cool feature. I'm working at the realization right now.

Did you think about the definition of the profiles on the model definition level? Also, what do you think about the `PartialSerializer<T>` to pick up only some fields from your model?

Example of the idea without `console.log().` I think you know what do I mean here 😃 :
```typescript
@Model({profiles: {
    reference: new PartialSerializer<User>(['id']),
    profileReference: new PartialSerializer<User>(['id', 'firstName', 'lastName', 'avatarUrl'])
}})
class User {
  @Field() id: number;
  @Field() firstName: string;
  @Field() lastName: string;
  @Field() avatarUrl: string;
  @Field() additionalHeavyInfo: SomeHeavyModel;
}
```

**Comment by breslavsky** [comment]
Hello @AndreyZelenskiy thanks a lot for the answer, but in your suggestion, we can have some narrow places:

1. We need to synchronize `string` property names with the structure of the model.
1. To build `Partial Serializer` into your library is not necessary because it is a special case. Another developer can have another.

Sorry for my pressure, but I think this code looks more strong :-):

```javascript
@Model()
class Issue {
  @Field() id: number;
  @Field() title: string;
  @Field({
    serializer: new ModelSerializer(User),
    profiles: {
      [SerializeProfiles.reference]: new ModelSerializer(Reference)
    }
  })
  user: User;
}
```
We have default serializer and special serializers for special cases.

**Comment by AndreyZelenskiy** [comment]
Thank you for your answer! I didn't find any pressure from you. It's just a discussion and thanks to you for that!
Regarding your first point. It could be a `keyof` from your type. You can find more info about it [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html).

About the second one. My main point was not about the serializer itself, more about the declaration of the possible profiles of this model. It could prevent you from searching every usage of this model and profile verification.

**Comment by breslavsky** [comment]
`keyof` looks good. Thanks.

Here the question was not about `declaration`, more about `serialization` using special profiles.

> It could prevent you from searching every usage of this model and profile verification.
If the profile was not defined, we use default serializer. I think it is not a problem.

So, which is the solution can be final?

**Comment by AndreyZelenskiy** [comment]
What do you think about `PartialSerializer`? I think it could solve your case with the reference type.
I will implement it in your way after it I think about the compatibility with the `Model` decorator.
Is it okay for you?

**Comment by breslavsky** [comment]
> P.S. It will be ready on Friday, I think.

Wow! Perfect! About `PartialSerializer`, you already have `ModelSerializer`. List of fields names can be a parameter.

**Comment by Gromov-Roman** [comment]
@AndreyZelenskiy Good issue, any updates here?

**Comment by protekshen** [comment]
Wow, it is will be very useful.

**Comment by AndreyZelenskiy** [comment]
@breslavsky I am trying to implement this feature and I have a strong feeling that it should be implemented via serializer because you have to notice that type in the field declaration.
So, right now I want to share this idea with you. Please check the code snippet and post feedback, please. Because I think it will be my realization of this feature.

**Comment by AndreyZelenskiy** [comment]
P.S. Also I think about the short factory methods to build serializers without a `new` keyword.

```typescript
class User {
    @Field({serializer: stringToNumberSerializer()})
    id: number;
}
```

**Comment by breslavsky** [comment]
> ```ts
> console.log(serialize(issue, SerializeProfiles.reference));
> ```

Wow, interesting idea. 

`SerializeProfiles.reference` will be passed into `serialize` function from `ProfileSerializer`?

What is about nested objects?

**Comment by AndreyZelenskiy** [comment]
The main idea that this profile info will be sent as extra information for the serializer. So, how to represent this profile it's not a big deal. I think we could implement it via field-profile map.

For example:

```typescript
serialize(issue, {user: SerializeProfiles.reference});
```

It will reduce the complexity of this solution and also provide a more flexible and well-typified structure of your code.

P.S. Theoretically this additional info should be generic to provide a possibility of creation super custom serializers.

**Comment by breslavsky** [comment]
As I understood changes will be here

https://github.com/AndreyZelenskiy/serialize/blob/master/src/converters/serialize.ts#L21

`return serializer.serialize.call([model, ... arguments]) || {};`

And it is all. We possible to pass parameters to the `serialize` method of the `serializer`.

**Comment by AndreyZelenskiy** [comment]
@breslavsky Hello, sorry for such a long delay! 😅Your feature is done.  I'm not so happy with the implementation details. But, it can cover your cases. Details of the usage are available here https://github.com/AndreyZelenskiy/serialize/blob/master/src/tests/profiles.spec.ts

Is it ok for you? Please, feel free to discuss the current version. I will add documentation and the section into the README file later. Now, I have only tests as documentation.😜
