### ISSUE TITLE
Errors in angular 8 projects

### ISSUE THREAD

**Issue by Gromov-Roman** [AndreyZelenskiy/serialize#28]
Errors appear during compilation of the project:

<img width="786" alt="Screenshot 2019-09-18 at 15 19 30" src="https://user-images.githubusercontent.com/20964736/65147976-eca00300-da27-11e9-8b62-76c672d4be5e.png">

 I believe that the error is related to the decision of the angular to remove variable nodes: 
https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

This issue is very urgent for us, please check it.

**Comment by breslavsky** [comment]
I have the same issue, we can't use Angular 8 :-(

**Comment by Gromov-Roman** [comment]
This error appears when I try to create object from class with Model decorator.

**Comment by breslavsky** [comment]
@Gromov-Roman could you provide code example?

**Comment by Gromov-Roman** [comment]
```
import { Model } from 'serialize-ts';
const persistence = Model;

@persistence()
export class Spec {
...
}

const spec = new Spec();
```

**Comment by AndreyZelenskiy** [comment]
@Gromov-Roman Could you provide an example on StackBlitz? I think it will be more productive to reproduce and fix this issue.

**Comment by Gromov-Roman** [comment]
@AndreyZelenskiy Sorry, it was problem with `import { hasOwnProperty } from 'tslint/lib/utils'`.

**Comment by Gromov-Roman** [comment]
Issue can be closed

**Comment by AndreyZelenskiy** [comment]
Thank you!
