### ISSUE TITLE
Exception when serializing not existing field with ArraySerializer

### ISSUE THREAD

**Issue by AndriiKobzar** [AndreyZelenskiy/serialize#3]
I am trying to serialize data from server, that contains optional array field. To do this, I mark field in model like this:
`@Field({
        serializer: new ArraySerializer<SampleModel>(new ModelSerializer(SampleModel)),
        jsonPropertyName: 'array'
    }) arrayOfObjects?: SampleModel[];`

However, during serialization i get "map is not a function" error.

It is caused by the fact that you pass empty object to serializer if field was not found in object.

**Comment by AndreyZelenskiy** [comment]
Fix this bug with #7 pull request
