### ISSUE TITLE
Deserialization returns empty object insted of zero

### ISSUE THREAD

**Issue by AndriiKobzar** [AndreyZelenskiy/serialize#4]
When using PrimitiveSerializer to deserialize 0, empty object is received instead. It happens because `0 || {} === {}` in setFieldMetadataToModel in deserialize.ts.

**Comment by AndreyZelenskiy** [comment]
#5 Pull request created - this will be in next patch of library

**Comment by AndreyZelenskiy** [comment]
@AndriiKobzar Do you want that exception was thrown if the field was not present but it was required?

**Comment by AndriiKobzar** [comment]
Yes, that would be nice

**Comment by AndreyZelenskiy** [comment]
#6 Optional support issue
