### ISSUE TITLE
@Serializer

### ISSUE THREAD

**Issue by DudaevAR** [AndreyZelenskiy/serialize#9]
In this example:
```
import { Field, Serializer } from 'serialize-ts';

class CustomSerializer implements Serializer<Object> {
    serialize(model: Object) {
        // Do some custom logic
    }

    deserialize(json: Object) {
        // Do your custom logic and return deserialized object
    }
}

class Model {
    @Field()
    @Serializer(new CustomSerializer())
    customField: any;
}
```
I get an error 
`Error: TS2693: 'Serializer' only refers to a type, but is being used as a value here.`

**Comment by AndreyZelenskiy** [comment]
It's problem with naming. You use Serializer interface as a decorator that's why you get such error. But now you are not able to import it, my fault. I will release a patch as soon as I can fix it. Thank you for a feedback

**Comment by AndreyZelenskiy** [comment]
@DudaevAR I fixed this issue. Serializer decorator was renamed for Type. I updated the README you are able to find new information there. If you have improvements or any new issues you are welcome) #12

**Comment by DudaevAR** [comment]
@AndreyZelenskiy Of course :)
